import MyReactQueryProvider from "@/providers/MyReactQueryProvider";
import { Toaster } from "sonner";

import "@/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <MyReactQueryProvider>
      <html lang="en">
        <body
          className={`h-screen bg-gradient-to-b from-[#2e026d] to-[#353871] font-sans text-white ${inter.variable}`}
        >
          {children}
          <Toaster />
        </body>
      </html>
    </MyReactQueryProvider>
  );
}
